/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.records;


import org.igsq.igsqbot.entities.jooq.tables.Reminders;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RemindersRecord extends UpdatableRecordImpl<RemindersRecord> implements Record4<Long, Long, Long, String>
{

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached RemindersRecord
	 */
	public RemindersRecord()
	{
		super(Reminders.REMINDERS);
	}

	/**
	 * Create a detached, initialised RemindersRecord
	 */
	public RemindersRecord(Long id, Long guildId, Long userId, String reminderText)
	{
		super(Reminders.REMINDERS);

		setId(id);
		setGuildId(guildId);
		setUserId(userId);
		setReminderText(reminderText);
	}

	/**
	 * Getter for <code>public.reminders.id</code>.
	 */
	public Long getId()
	{
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.reminders.id</code>.
	 */
	public RemindersRecord setId(Long value)
	{
		set(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.reminders.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.reminders.guild_id</code>.
	 */
	public RemindersRecord setGuildId(Long value)
	{
		set(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.reminders.user_id</code>.
	 */
	public Long getUserId()
	{
		return (Long) get(2);
	}

	/**
	 * Setter for <code>public.reminders.user_id</code>.
	 */
	public RemindersRecord setUserId(Long value)
	{
		set(2, value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.reminders.reminder_text</code>.
	 */
	public String getReminderText()
	{
		return (String) get(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.reminders.reminder_text</code>.
	 */
	public RemindersRecord setReminderText(String value)
	{
		set(3, value);
		return this;
	}

	@Override
	public Record1<Long> key()
	{
		return (Record1) super.key();
	}

	@Override
	public Row4<Long, Long, Long, String> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}

	@Override
	public Row4<Long, Long, Long, String> valuesRow()
	{
		return (Row4) super.valuesRow();
	}

	@Override
	public Field<Long> field1()
	{
		return Reminders.REMINDERS.ID;
	}

	@Override
	public Field<Long> field2()
	{
		return Reminders.REMINDERS.GUILD_ID;
	}

	@Override
	public Field<Long> field3()
	{
		return Reminders.REMINDERS.USER_ID;
	}

	@Override
	public Field<String> field4()
	{
		return Reminders.REMINDERS.REMINDER_TEXT;
	}

	@Override
	public Long component1()
	{
		return getId();
	}

	@Override
	public Long component2()
	{
		return getGuildId();
	}

	@Override
	public Long component3()
	{
		return getUserId();
	}

	@Override
	public String component4()
	{
		return getReminderText();
	}

	@Override
	public Long value1()
	{
		return getId();
	}

	@Override
	public Long value2()
	{
		return getGuildId();
	}

	@Override
	public Long value3()
	{
		return getUserId();
	}

	@Override
	public String value4()
	{
		return getReminderText();
	}

	@Override
	public RemindersRecord value1(Long value)
	{
		setId(value);
		return this;
	}

	@Override
	public RemindersRecord value2(Long value)
	{
		setGuildId(value);
		return this;
	}

	@Override
	public RemindersRecord value3(Long value)
	{
		setUserId(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	@Override
	public RemindersRecord value4(String value)
	{
		setReminderText(value);
		return this;
	}

	@Override
	public RemindersRecord values(Long value1, Long value2, Long value3, String value4)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}
}
