/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.records;


import java.time.LocalDateTime;
import org.igsq.igsqbot.entities.jooq.tables.Votes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class VotesRecord extends UpdatableRecordImpl<VotesRecord>
		implements Record9<Long, Long, Long, Long, Long, Integer, Integer, LocalDateTime, Boolean>
{

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached VotesRecord
	 */
	public VotesRecord()
	{
		super(Votes.VOTES);
	}

	/**
	 * Create a detached, initialised VotesRecord
	 */
	public VotesRecord(Long id, Long voteId, Long guildId, Long directMessageId, Long userId, Integer option, Integer maxOptions, LocalDateTime expiry, Boolean hasVoted)
	{
		super(Votes.VOTES);

		setId(id);
		setVoteId(voteId);
		setGuildId(guildId);
		setDirectMessageId(directMessageId);
		setUserId(userId);
		setOption(option);
		setMaxOptions(maxOptions);
		setExpiry(expiry);
		setHasVoted(hasVoted);
	}

	/**
	 * Getter for <code>public.votes.id</code>.
	 */
	public Long getId()
	{
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.votes.id</code>.
	 */
	public VotesRecord setId(Long value)
	{
		set(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.vote_id</code>.
	 */
	public Long getVoteId()
	{
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.votes.vote_id</code>.
	 */
	public VotesRecord setVoteId(Long value)
	{
		set(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return (Long) get(2);
	}

	/**
	 * Setter for <code>public.votes.guild_id</code>.
	 */
	public VotesRecord setGuildId(Long value)
	{
		set(2, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.direct_message_id</code>.
	 */
	public Long getDirectMessageId()
	{
		return (Long) get(3);
	}

	/**
	 * Setter for <code>public.votes.direct_message_id</code>.
	 */
	public VotesRecord setDirectMessageId(Long value)
	{
		set(3, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.user_id</code>.
	 */
	public Long getUserId()
	{
		return (Long) get(4);
	}

	/**
	 * Setter for <code>public.votes.user_id</code>.
	 */
	public VotesRecord setUserId(Long value)
	{
		set(4, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.option</code>.
	 */
	public Integer getOption()
	{
		return (Integer) get(5);
	}

	/**
	 * Setter for <code>public.votes.option</code>.
	 */
	public VotesRecord setOption(Integer value)
	{
		set(5, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.max_options</code>.
	 */
	public Integer getMaxOptions()
	{
		return (Integer) get(6);
	}

	/**
	 * Setter for <code>public.votes.max_options</code>.
	 */
	public VotesRecord setMaxOptions(Integer value)
	{
		set(6, value);
		return this;
	}

	/**
	 * Getter for <code>public.votes.expiry</code>.
	 */
	public LocalDateTime getExpiry()
	{
		return (LocalDateTime) get(7);
	}

	/**
	 * Setter for <code>public.votes.expiry</code>.
	 */
	public VotesRecord setExpiry(LocalDateTime value)
	{
		set(7, value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.votes.has_voted</code>.
	 */
	public Boolean getHasVoted()
	{
		return (Boolean) get(8);
	}

	// -------------------------------------------------------------------------
	// Record9 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.votes.has_voted</code>.
	 */
	public VotesRecord setHasVoted(Boolean value)
	{
		set(8, value);
		return this;
	}

	@Override
	public Record1<Long> key()
	{
		return (Record1) super.key();
	}

	@Override
	public Row9<Long, Long, Long, Long, Long, Integer, Integer, LocalDateTime, Boolean> fieldsRow()
	{
		return (Row9) super.fieldsRow();
	}

	@Override
	public Row9<Long, Long, Long, Long, Long, Integer, Integer, LocalDateTime, Boolean> valuesRow()
	{
		return (Row9) super.valuesRow();
	}

	@Override
	public Field<Long> field1()
	{
		return Votes.VOTES.ID;
	}

	@Override
	public Field<Long> field2()
	{
		return Votes.VOTES.VOTE_ID;
	}

	@Override
	public Field<Long> field3()
	{
		return Votes.VOTES.GUILD_ID;
	}

	@Override
	public Field<Long> field4()
	{
		return Votes.VOTES.DIRECT_MESSAGE_ID;
	}

	@Override
	public Field<Long> field5()
	{
		return Votes.VOTES.USER_ID;
	}

	@Override
	public Field<Integer> field6()
	{
		return Votes.VOTES.OPTION;
	}

	@Override
	public Field<Integer> field7()
	{
		return Votes.VOTES.MAX_OPTIONS;
	}

	@Override
	public Field<LocalDateTime> field8()
	{
		return Votes.VOTES.EXPIRY;
	}

	@Override
	public Field<Boolean> field9()
	{
		return Votes.VOTES.HAS_VOTED;
	}

	@Override
	public Long component1()
	{
		return getId();
	}

	@Override
	public Long component2()
	{
		return getVoteId();
	}

	@Override
	public Long component3()
	{
		return getGuildId();
	}

	@Override
	public Long component4()
	{
		return getDirectMessageId();
	}

	@Override
	public Long component5()
	{
		return getUserId();
	}

	@Override
	public Integer component6()
	{
		return getOption();
	}

	@Override
	public Integer component7()
	{
		return getMaxOptions();
	}

	@Override
	public LocalDateTime component8()
	{
		return getExpiry();
	}

	@Override
	public Boolean component9()
	{
		return getHasVoted();
	}

	@Override
	public Long value1()
	{
		return getId();
	}

	@Override
	public Long value2()
	{
		return getVoteId();
	}

	@Override
	public Long value3()
	{
		return getGuildId();
	}

	@Override
	public Long value4()
	{
		return getDirectMessageId();
	}

	@Override
	public Long value5()
	{
		return getUserId();
	}

	@Override
	public Integer value6()
	{
		return getOption();
	}

	@Override
	public Integer value7()
	{
		return getMaxOptions();
	}

	@Override
	public LocalDateTime value8()
	{
		return getExpiry();
	}

	@Override
	public Boolean value9()
	{
		return getHasVoted();
	}

	@Override
	public VotesRecord value1(Long value)
	{
		setId(value);
		return this;
	}

	@Override
	public VotesRecord value2(Long value)
	{
		setVoteId(value);
		return this;
	}

	@Override
	public VotesRecord value3(Long value)
	{
		setGuildId(value);
		return this;
	}

	@Override
	public VotesRecord value4(Long value)
	{
		setDirectMessageId(value);
		return this;
	}

	@Override
	public VotesRecord value5(Long value)
	{
		setUserId(value);
		return this;
	}

	@Override
	public VotesRecord value6(Integer value)
	{
		setOption(value);
		return this;
	}

	@Override
	public VotesRecord value7(Integer value)
	{
		setMaxOptions(value);
		return this;
	}

	@Override
	public VotesRecord value8(LocalDateTime value)
	{
		setExpiry(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	@Override
	public VotesRecord value9(Boolean value)
	{
		setHasVoted(value);
		return this;
	}

	@Override
	public VotesRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Integer value6, Integer value7, LocalDateTime value8, Boolean value9)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		value9(value9);
		return this;
	}
}
