/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables;


import java.util.Arrays;
import java.util.List;
import org.igsq.igsqbot.entities.jooq.Keys;
import org.igsq.igsqbot.entities.jooq.Public;
import org.igsq.igsqbot.entities.jooq.tables.records.LevelsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Levels extends TableImpl<LevelsRecord>
{

	/**
	 * The reference instance of <code>public.levels</code>
	 */
	public static final Levels LEVELS = new Levels();
	private static final long serialVersionUID = 1L;
	/**
	 * The column <code>public.levels.id</code>.
	 */
	public final TableField<LevelsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
	/**
	 * The column <code>public.levels.guild_id</code>.
	 */
	public final TableField<LevelsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");
	/**
	 * The column <code>public.levels.role_id</code>.
	 */
	public final TableField<LevelsRecord, Long> ROLE_ID = createField(DSL.name("role_id"), SQLDataType.BIGINT.nullable(false), this, "");
	/**
	 * The column <code>public.levels.awarded_at</code>.
	 */
	public final TableField<LevelsRecord, Integer> AWARDED_AT = createField(DSL.name("awarded_at"), SQLDataType.INTEGER.nullable(false), this, "");

	private Levels(Name alias, Table<LevelsRecord> aliased)
	{
		this(alias, aliased, null);
	}

	private Levels(Name alias, Table<LevelsRecord> aliased, Field<?>[] parameters)
	{
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	/**
	 * Create an aliased <code>public.levels</code> table reference
	 */
	public Levels(String alias)
	{
		this(DSL.name(alias), LEVELS);
	}

	/**
	 * Create an aliased <code>public.levels</code> table reference
	 */
	public Levels(Name alias)
	{
		this(alias, LEVELS);
	}

	/**
	 * Create a <code>public.levels</code> table reference
	 */
	public Levels()
	{
		this(DSL.name("levels"), null);
	}

	public <O extends Record> Levels(Table<O> child, ForeignKey<O, LevelsRecord> key)
	{
		super(child, key, LEVELS);
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<LevelsRecord> getRecordType()
	{
		return LevelsRecord.class;
	}

	@Override
	public Schema getSchema()
	{
		return Public.PUBLIC;
	}

	@Override
	public Identity<LevelsRecord, Long> getIdentity()
	{
		return (Identity<LevelsRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<LevelsRecord> getPrimaryKey()
	{
		return Keys.LEVELS_PKEY;
	}

	@Override
	public List<UniqueKey<LevelsRecord>> getKeys()
	{
		return Arrays.<UniqueKey<LevelsRecord>>asList(Keys.LEVELS_PKEY);
	}

	@Override
	public Levels as(String alias)
	{
		return new Levels(DSL.name(alias), this);
	}

	@Override
	public Levels as(Name alias)
	{
		return new Levels(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Levels rename(String name)
	{
		return new Levels(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Levels rename(Name name)
	{
		return new Levels(name, null);
	}

	// -------------------------------------------------------------------------
	// Row4 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row4<Long, Long, Long, Integer> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}
}
