/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables;


import java.util.Arrays;
import java.util.List;
import org.igsq.igsqbot.entities.jooq.Keys;
import org.igsq.igsqbot.entities.jooq.Public;
import org.igsq.igsqbot.entities.jooq.tables.records.RemindersRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Reminders extends TableImpl<RemindersRecord>
{

	/**
	 * The reference instance of <code>public.reminders</code>
	 */
	public static final Reminders REMINDERS = new Reminders();
	private static final long serialVersionUID = 1L;
	/**
	 * The column <code>public.reminders.id</code>.
	 */
	public final TableField<RemindersRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
	/**
	 * The column <code>public.reminders.guild_id</code>.
	 */
	public final TableField<RemindersRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");
	/**
	 * The column <code>public.reminders.user_id</code>.
	 */
	public final TableField<RemindersRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "");
	/**
	 * The column <code>public.reminders.reminder_text</code>.
	 */
	public final TableField<RemindersRecord, String> REMINDER_TEXT = createField(DSL.name("reminder_text"), SQLDataType.CLOB.nullable(false), this, "");

	private Reminders(Name alias, Table<RemindersRecord> aliased)
	{
		this(alias, aliased, null);
	}

	private Reminders(Name alias, Table<RemindersRecord> aliased, Field<?>[] parameters)
	{
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	/**
	 * Create an aliased <code>public.reminders</code> table reference
	 */
	public Reminders(String alias)
	{
		this(DSL.name(alias), REMINDERS);
	}

	/**
	 * Create an aliased <code>public.reminders</code> table reference
	 */
	public Reminders(Name alias)
	{
		this(alias, REMINDERS);
	}

	/**
	 * Create a <code>public.reminders</code> table reference
	 */
	public Reminders()
	{
		this(DSL.name("reminders"), null);
	}

	public <O extends Record> Reminders(Table<O> child, ForeignKey<O, RemindersRecord> key)
	{
		super(child, key, REMINDERS);
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RemindersRecord> getRecordType()
	{
		return RemindersRecord.class;
	}

	@Override
	public Schema getSchema()
	{
		return Public.PUBLIC;
	}

	@Override
	public Identity<RemindersRecord, Long> getIdentity()
	{
		return (Identity<RemindersRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<RemindersRecord> getPrimaryKey()
	{
		return Keys.REMINDERS_PKEY;
	}

	@Override
	public List<UniqueKey<RemindersRecord>> getKeys()
	{
		return Arrays.<UniqueKey<RemindersRecord>>asList(Keys.REMINDERS_PKEY);
	}

	@Override
	public Reminders as(String alias)
	{
		return new Reminders(DSL.name(alias), this);
	}

	@Override
	public Reminders as(Name alias)
	{
		return new Reminders(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Reminders rename(String name)
	{
		return new Reminders(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public Reminders rename(Name name)
	{
		return new Reminders(name, null);
	}

	// -------------------------------------------------------------------------
	// Row4 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row4<Long, Long, Long, String> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}
}
