/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables;


import java.util.Arrays;
import java.util.List;
import org.igsq.igsqbot.entities.jooq.Keys;
import org.igsq.igsqbot.entities.jooq.Public;
import org.igsq.igsqbot.entities.jooq.tables.records.WordBlacklistsRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WordBlacklists extends TableImpl<WordBlacklistsRecord>
{

	/**
	 * The reference instance of <code>public.word_blacklists</code>
	 */
	public static final WordBlacklists WORD_BLACKLISTS = new WordBlacklists();
	private static final long serialVersionUID = 1L;
	/**
	 * The column <code>public.word_blacklists.id</code>.
	 */
	public final TableField<WordBlacklistsRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");
	/**
	 * The column <code>public.word_blacklists.guild_id</code>.
	 */
	public final TableField<WordBlacklistsRecord, Long> GUILD_ID = createField(DSL.name("guild_id"), SQLDataType.BIGINT.nullable(false), this, "");
	/**
	 * The column <code>public.word_blacklists.phrase</code>.
	 */
	public final TableField<WordBlacklistsRecord, String> PHRASE = createField(DSL.name("phrase"), SQLDataType.CLOB.nullable(false), this, "");

	private WordBlacklists(Name alias, Table<WordBlacklistsRecord> aliased)
	{
		this(alias, aliased, null);
	}

	private WordBlacklists(Name alias, Table<WordBlacklistsRecord> aliased, Field<?>[] parameters)
	{
		super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
	}

	/**
	 * Create an aliased <code>public.word_blacklists</code> table reference
	 */
	public WordBlacklists(String alias)
	{
		this(DSL.name(alias), WORD_BLACKLISTS);
	}

	/**
	 * Create an aliased <code>public.word_blacklists</code> table reference
	 */
	public WordBlacklists(Name alias)
	{
		this(alias, WORD_BLACKLISTS);
	}

	/**
	 * Create a <code>public.word_blacklists</code> table reference
	 */
	public WordBlacklists()
	{
		this(DSL.name("word_blacklists"), null);
	}

	public <O extends Record> WordBlacklists(Table<O> child, ForeignKey<O, WordBlacklistsRecord> key)
	{
		super(child, key, WORD_BLACKLISTS);
	}

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<WordBlacklistsRecord> getRecordType()
	{
		return WordBlacklistsRecord.class;
	}

	@Override
	public Schema getSchema()
	{
		return Public.PUBLIC;
	}

	@Override
	public Identity<WordBlacklistsRecord, Long> getIdentity()
	{
		return (Identity<WordBlacklistsRecord, Long>) super.getIdentity();
	}

	@Override
	public UniqueKey<WordBlacklistsRecord> getPrimaryKey()
	{
		return Keys.WORD_BLACKLISTS_PKEY;
	}

	@Override
	public List<UniqueKey<WordBlacklistsRecord>> getKeys()
	{
		return Arrays.<UniqueKey<WordBlacklistsRecord>>asList(Keys.WORD_BLACKLISTS_PKEY);
	}

	@Override
	public WordBlacklists as(String alias)
	{
		return new WordBlacklists(DSL.name(alias), this);
	}

	@Override
	public WordBlacklists as(Name alias)
	{
		return new WordBlacklists(alias, this);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WordBlacklists rename(String name)
	{
		return new WordBlacklists(DSL.name(name), null);
	}

	/**
	 * Rename this table
	 */
	@Override
	public WordBlacklists rename(Name name)
	{
		return new WordBlacklists(name, null);
	}

	// -------------------------------------------------------------------------
	// Row3 type methods
	// -------------------------------------------------------------------------

	@Override
	public Row3<Long, Long, String> fieldsRow()
	{
		return (Row3) super.fieldsRow();
	}
}
