/*
 * This file is generated by jOOQ.
 */
package me.arynxd.monkebot.objects.jooq.tables.records;


import me.arynxd.monkebot.objects.jooq.tables.Roles;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings ({"all", "unchecked", "rawtypes"})
public class RolesRecord extends UpdatableRecordImpl<RolesRecord> implements Record4<Long, Long, Long, Long>
{

	private static final long serialVersionUID = 1L;

	/**
	 * Create a detached RolesRecord
	 */
	public RolesRecord()
	{
		super(Roles.ROLES);
	}

	/**
	 * Create a detached, initialised RolesRecord
	 */
	public RolesRecord(Long id, Long userId, Long guildId, Long roleId)
	{
		super(Roles.ROLES);

		setId(id);
		setUserId(userId);
		setGuildId(guildId);
		setRoleId(roleId);
	}

	/**
	 * Getter for <code>public.roles.id</code>.
	 */
	public Long getId()
	{
		return (Long) get(0);
	}

	/**
	 * Setter for <code>public.roles.id</code>.
	 */
	public RolesRecord setId(Long value)
	{
		set(0, value);
		return this;
	}

	/**
	 * Getter for <code>public.roles.user_id</code>.
	 */
	public Long getUserId()
	{
		return (Long) get(1);
	}

	/**
	 * Setter for <code>public.roles.user_id</code>.
	 */
	public RolesRecord setUserId(Long value)
	{
		set(1, value);
		return this;
	}

	/**
	 * Getter for <code>public.roles.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return (Long) get(2);
	}

	/**
	 * Setter for <code>public.roles.guild_id</code>.
	 */
	public RolesRecord setGuildId(Long value)
	{
		set(2, value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>public.roles.role_id</code>.
	 */
	public Long getRoleId()
	{
		return (Long) get(3);
	}

	// -------------------------------------------------------------------------
	// Record4 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>public.roles.role_id</code>.
	 */
	public RolesRecord setRoleId(Long value)
	{
		set(3, value);
		return this;
	}

	@Override
	public Record1<Long> key()
	{
		return (Record1) super.key();
	}

	@Override
	public Row4<Long, Long, Long, Long> fieldsRow()
	{
		return (Row4) super.fieldsRow();
	}

	@Override
	public Row4<Long, Long, Long, Long> valuesRow()
	{
		return (Row4) super.valuesRow();
	}

	@Override
	public Field<Long> field1()
	{
		return Roles.ROLES.ID;
	}

	@Override
	public Field<Long> field2()
	{
		return Roles.ROLES.USER_ID;
	}

	@Override
	public Field<Long> field3()
	{
		return Roles.ROLES.GUILD_ID;
	}

	@Override
	public Field<Long> field4()
	{
		return Roles.ROLES.ROLE_ID;
	}

	@Override
	public Long component1()
	{
		return getId();
	}

	@Override
	public Long component2()
	{
		return getUserId();
	}

	@Override
	public Long component3()
	{
		return getGuildId();
	}

	@Override
	public Long component4()
	{
		return getRoleId();
	}

	@Override
	public Long value1()
	{
		return getId();
	}

	@Override
	public Long value2()
	{
		return getUserId();
	}

	@Override
	public Long value3()
	{
		return getGuildId();
	}

	@Override
	public Long value4()
	{
		return getRoleId();
	}

	@Override
	public RolesRecord value1(Long value)
	{
		setId(value);
		return this;
	}

	@Override
	public RolesRecord value2(Long value)
	{
		setUserId(value);
		return this;
	}

	@Override
	public RolesRecord value3(Long value)
	{
		setGuildId(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	@Override
	public RolesRecord value4(Long value)
	{
		setRoleId(value);
		return this;
	}

	@Override
	public RolesRecord values(Long value1, Long value2, Long value3, Long value4)
	{
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		return this;
	}
}
