/*
 * This file is generated by jOOQ.
 */
package me.arynxd.monkebot.entities.jooq;


import me.arynxd.monkebot.entities.jooq.tables.ChannelBlacklists;
import me.arynxd.monkebot.entities.jooq.tables.ReactionRoles;
import me.arynxd.monkebot.entities.jooq.tables.Reminders;
import me.arynxd.monkebot.entities.jooq.tables.Guilds;
import me.arynxd.monkebot.entities.jooq.tables.Levels;
import me.arynxd.monkebot.entities.jooq.tables.Reports;
import me.arynxd.monkebot.entities.jooq.tables.Roles;
import me.arynxd.monkebot.entities.jooq.tables.Tempbans;
import me.arynxd.monkebot.entities.jooq.tables.Verification;
import me.arynxd.monkebot.entities.jooq.tables.Votes;
import me.arynxd.monkebot.entities.jooq.tables.Warnings;
import me.arynxd.monkebot.entities.jooq.tables.WordBlacklists;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.channel_blacklists</code>.
     */
    public static final ChannelBlacklists CHANNEL_BLACKLISTS = ChannelBlacklists.CHANNEL_BLACKLISTS;

    /**
     * The table <code>public.guilds</code>.
     */
    public static final Guilds GUILDS = Guilds.GUILDS;

    /**
     * The table <code>public.levels</code>.
     */
    public static final Levels LEVELS = Levels.LEVELS;

    /**
     * The table <code>public.reaction_roles</code>.
     */
    public static final ReactionRoles REACTION_ROLES = ReactionRoles.REACTION_ROLES;

    /**
     * The table <code>public.reminders</code>.
     */
    public static final Reminders REMINDERS = Reminders.REMINDERS;

    /**
     * The table <code>public.reports</code>.
     */
    public static final Reports REPORTS = Reports.REPORTS;

    /**
     * The table <code>public.roles</code>.
     */
    public static final Roles ROLES = Roles.ROLES;

    /**
     * The table <code>public.tempbans</code>.
     */
    public static final Tempbans TEMPBANS = Tempbans.TEMPBANS;

    /**
     * The table <code>public.verification</code>.
     */
    public static final Verification VERIFICATION = Verification.VERIFICATION;

    /**
     * The table <code>public.votes</code>.
     */
    public static final Votes VOTES = Votes.VOTES;

    /**
     * The table <code>public.warnings</code>.
     */
    public static final Warnings WARNINGS = Warnings.WARNINGS;

    /**
     * The table <code>public.word_blacklists</code>.
     */
    public static final WordBlacklists WORD_BLACKLISTS = WordBlacklists.WORD_BLACKLISTS;
}
