/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ChannelBlacklists implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long id;
	private final Long guildId;
	private final Long channelId;

	public ChannelBlacklists(ChannelBlacklists value)
	{
		this.id = value.id;
		this.guildId = value.guildId;
		this.channelId = value.channelId;
	}

	public ChannelBlacklists(
			Long id,
			Long guildId,
			Long channelId
	)
	{
		this.id = id;
		this.guildId = guildId;
		this.channelId = channelId;
	}

	/**
	 * Getter for <code>public.channel_blacklists.id</code>.
	 */
	public Long getId()
	{
		return this.id;
	}

	/**
	 * Getter for <code>public.channel_blacklists.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return this.guildId;
	}

	/**
	 * Getter for <code>public.channel_blacklists.channel_id</code>.
	 */
	public Long getChannelId()
	{
		return this.channelId;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("ChannelBlacklists (");

		sb.append(id);
		sb.append(", ").append(guildId);
		sb.append(", ").append(channelId);

		sb.append(")");
		return sb.toString();
	}
}
