/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ReactionRoles implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long id;
	private final Long messageId;
	private final Long guildId;
	private final String emoteId;
	private final Long roleId;

	public ReactionRoles(ReactionRoles value)
	{
		this.id = value.id;
		this.messageId = value.messageId;
		this.guildId = value.guildId;
		this.emoteId = value.emoteId;
		this.roleId = value.roleId;
	}

	public ReactionRoles(
			Long id,
			Long messageId,
			Long guildId,
			String emoteId,
			Long roleId
	)
	{
		this.id = id;
		this.messageId = messageId;
		this.guildId = guildId;
		this.emoteId = emoteId;
		this.roleId = roleId;
	}

	/**
	 * Getter for <code>public.reaction_roles.id</code>.
	 */
	public Long getId()
	{
		return this.id;
	}

	/**
	 * Getter for <code>public.reaction_roles.message_id</code>.
	 */
	public Long getMessageId()
	{
		return this.messageId;
	}

	/**
	 * Getter for <code>public.reaction_roles.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return this.guildId;
	}

	/**
	 * Getter for <code>public.reaction_roles.emote_id</code>.
	 */
	public String getEmoteId()
	{
		return this.emoteId;
	}

	/**
	 * Getter for <code>public.reaction_roles.role_id</code>.
	 */
	public Long getRoleId()
	{
		return this.roleId;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("ReactionRoles (");

		sb.append(id);
		sb.append(", ").append(messageId);
		sb.append(", ").append(guildId);
		sb.append(", ").append(emoteId);
		sb.append(", ").append(roleId);

		sb.append(")");
		return sb.toString();
	}
}
