/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Reminders implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long id;
	private final Long guildId;
	private final Long userId;
	private final String reminderText;

	public Reminders(Reminders value)
	{
		this.id = value.id;
		this.guildId = value.guildId;
		this.userId = value.userId;
		this.reminderText = value.reminderText;
	}

	public Reminders(
			Long id,
			Long guildId,
			Long userId,
			String reminderText
	)
	{
		this.id = id;
		this.guildId = guildId;
		this.userId = userId;
		this.reminderText = reminderText;
	}

	/**
	 * Getter for <code>public.reminders.id</code>.
	 */
	public Long getId()
	{
		return this.id;
	}

	/**
	 * Getter for <code>public.reminders.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return this.guildId;
	}

	/**
	 * Getter for <code>public.reminders.user_id</code>.
	 */
	public Long getUserId()
	{
		return this.userId;
	}

	/**
	 * Getter for <code>public.reminders.reminder_text</code>.
	 */
	public String getReminderText()
	{
		return this.reminderText;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Reminders (");

		sb.append(id);
		sb.append(", ").append(guildId);
		sb.append(", ").append(userId);
		sb.append(", ").append(reminderText);

		sb.append(")");
		return sb.toString();
	}
}
