/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tempbans implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long id;
	private final Long userId;
	private final Long guildId;
	private final LocalDateTime mutedUntil;

	public Tempbans(Tempbans value)
	{
		this.id = value.id;
		this.userId = value.userId;
		this.guildId = value.guildId;
		this.mutedUntil = value.mutedUntil;
	}

	public Tempbans(
			Long id,
			Long userId,
			Long guildId,
			LocalDateTime mutedUntil
	)
	{
		this.id = id;
		this.userId = userId;
		this.guildId = guildId;
		this.mutedUntil = mutedUntil;
	}

	/**
	 * Getter for <code>public.tempbans.id</code>.
	 */
	public Long getId()
	{
		return this.id;
	}

	/**
	 * Getter for <code>public.tempbans.user_id</code>.
	 */
	public Long getUserId()
	{
		return this.userId;
	}

	/**
	 * Getter for <code>public.tempbans.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return this.guildId;
	}

	/**
	 * Getter for <code>public.tempbans.muted_until</code>.
	 */
	public LocalDateTime getMutedUntil()
	{
		return this.mutedUntil;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Tempbans (");

		sb.append(id);
		sb.append(", ").append(userId);
		sb.append(", ").append(guildId);
		sb.append(", ").append(mutedUntil);

		sb.append(")");
		return sb.toString();
	}
}
