/*
 * This file is generated by jOOQ.
 */
package org.igsq.igsqbot.entities.jooq.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Warnings implements Serializable
{

	private static final long serialVersionUID = 1L;

	private final Long id;
	private final Long guildId;
	private final Long userId;
	private final LocalDateTime timestamp;
	private final String warnText;

	public Warnings(Warnings value)
	{
		this.id = value.id;
		this.guildId = value.guildId;
		this.userId = value.userId;
		this.timestamp = value.timestamp;
		this.warnText = value.warnText;
	}

	public Warnings(
			Long id,
			Long guildId,
			Long userId,
			LocalDateTime timestamp,
			String warnText
	)
	{
		this.id = id;
		this.guildId = guildId;
		this.userId = userId;
		this.timestamp = timestamp;
		this.warnText = warnText;
	}

	/**
	 * Getter for <code>public.warnings.id</code>.
	 */
	public Long getId()
	{
		return this.id;
	}

	/**
	 * Getter for <code>public.warnings.guild_id</code>.
	 */
	public Long getGuildId()
	{
		return this.guildId;
	}

	/**
	 * Getter for <code>public.warnings.user_id</code>.
	 */
	public Long getUserId()
	{
		return this.userId;
	}

	/**
	 * Getter for <code>public.warnings.timestamp</code>.
	 */
	public LocalDateTime getTimestamp()
	{
		return this.timestamp;
	}

	/**
	 * Getter for <code>public.warnings.warn_text</code>.
	 */
	public String getWarnText()
	{
		return this.warnText;
	}

	@Override
	public String toString()
	{
		StringBuilder sb = new StringBuilder("Warnings (");

		sb.append(id);
		sb.append(", ").append(guildId);
		sb.append(", ").append(userId);
		sb.append(", ").append(timestamp);
		sb.append(", ").append(warnText);

		sb.append(")");
		return sb.toString();
	}
}
